In [1]:
import numpy as np

In [2]:
a=np.arange(5)

In [3]:
a

array([0, 1, 2, 3, 4])

In [4]:
a[1]

1

In [5]:
a[1,3]

IndexError: too many indices for array

In [6]:
a[[1]]

array([1])

In [7]:
a=[4,5,6,7,8]

In [8]:
a[1]

5

In [9]:
a[[1,3]]

TypeError: list indices must be integers or slices, not list

In [10]:
a=np.arange(5)

In [11]:
a

array([0, 1, 2, 3, 4])

In [12]:
a[[1,3]]

array([1, 3])

In [27]:
b=np.arange(12).reshape((3,4))

In [28]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
b[[0,2], [2,3]]

array([ 2, 11])

In [31]:
b[0,2]

2